[package]
authors = ["Rust-IPFS contributors"]
description = "UnixFs tree support"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "ipfs-unixfs"
readme = "README.md"
repository = "https://github.com/rs-ipfs/rust-ipfs"
version = "0.2.0"

[features]
default = ["filetime"]

[dependencies]
cid = { default-features = false, version = "0.7", features = ["std"] }
either = { default-features = false, version = "1.5" }
filetime = { optional = true, version = "0.2.12" }
multihash = { default-features = false, version = "0.14", features = ["multihash-impl", "std", "secure-hashes"] }
quick-protobuf = { default-features = false, features = ["std"], version = "0.8" }
sha2 = { default-features = false, version = "0.9" }

[dev-dependencies]
hash_hasher = "2.0.3"
hex-literal = { default-features = false, version = "0.3" }
libc = { default-features = false, version = "0.2.71" }
multibase = { default-features = false, version = "0.9.1" }
tar = { default-features = false, version = "0.4" }
criterion = { default-features = false, version = "0.3" }

[[bench]]
name = "ingest-tar"
harness = false

[[bench]]
name = "adder"
harness = false
